# Site
repository: norlancd/norlancd.github.io
# favicon: images/favicon.ico

# Personal info
name: Norlan Capote
title: Senior Developer
email: norlan.capote@gmail.com
website: https://github.com/norlancd/norlancd.github.io

# Social links
twitter_username: norlancd
github_username:  norlancd
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: norlancd
pinterest_username: norlancd
youtube_username: norlan.capote
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/photo_perfil.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Norlan and I'm a Scrum Master and a senior developer in different programming languages. 
  I have experience making Web and Mobile applications. 
  
  I am most skilled in: <mark>C#</mark> and <mark>Odoo</mark>

  |◼️ Computer Science Engineer, with 10 years of experience in testing, development and maintenance of Web applications, Mobile and Desktop in different programming languages ​​applying agile methodologies.
  |◼️ Analyst Software Developer with knowledge of Computer Architecture, Network Architecture, Computer Security, Software Engineering, Process Automation, Software and Project Management, Requirements Capture, Software Quality Assurance (QA), Risk Management, and Software Architecture.
  |◼️ Highly responsible, honest professional, focused on their objectives, with excellent analytical skills and problem solving.
  |◼️ Passionate about finding technological solutions that add value to the services he carries out and with a permanent disposition to share his knowledge with others. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software developer and software engineering some of my other interests and hobbies are:
   - Science fiction
   - Space

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
